using System;
using System.Collections.Generic;
namespace AnimalIdentifier_Base
{
    public static class ProgramText
    {

        static void Main()
        {
            Console.WriteLine("Enter a path");
            string path = Console.ReadLine();

            List<Tag> tags = C_Input.Input(path);
            //Testing if any tags are returned
            //foreach (Tag tag in tags)
            //{
            //    Console.WriteLine(tag.name);
            //}

            Console.WriteLine("These are the tags generated by the image, with a confidence of greater than 80%: ");

            var filter = new TagFilter();
            tags = filter.Filter(tags);


            if (tags != null && tags.Count > 0) //Exception handling
            {


                foreach (var tag in tags)
                {
                    Console.WriteLine($"image contains {tag.name}");
                }
            }
            else
            {
                Console.WriteLine("We're sorry, but the image did not return any tags. The program will now terminate.");

            }

            Console.WriteLine("Press Any Key to Continue.");
            Console.ReadLine();
        }
    }
}
